### ISSUE TITLE
try_get_with always runs init future

### ISSUE THREAD

**Issue by dannygale** [moka-rs/moka#208] opened 2022-12-13 04:23 UTC
It seems like `moka::future::Cache::try_get_with` and `try_get_with_by_ref` always run the provided init future to completion, and then throw away its value. Interestingly, `get_with` does not show this behavior. I've tried to make the simplest possible example of this behavior:

```rust
use futures::future;
use moka::future::Cache;
use std::hash::Hash;
use std::path::PathBuf;
use std::time::Duration;

async fn init<K: Hash + Eq + Send + Sync + Clone + 'static>(
    cache: Cache<K, u32>,
    key: &K,
    value: u32,
) -> u32 {
    if cache.contains_key(&key) {
        println!("cache contains key but init triggered anyway");
    }
    tokio::time::sleep(Duration::from_millis(1000)).await;
    println!("init ran to completion");
    value
}

fn check_result(result: u32) {
    println!("result: {:?}", &result);
    println!(
        "result was returned from {}",
        if result == 1 {
            "cache"
        } else {
            "init function"
        }
    );
}

#[tokio::main]
async fn main() {
    let cache = Cache::new(100);

    let key = PathBuf::from("asdf");

    cache.insert(key.clone(), 1).await;

    println!("--- checking try_get_with_by_ref ---");

    let result = cache
        .try_get_with_by_ref(
            &key,
            future::ok::<u32, u32>(init(cache.clone(), &key, 2).await),
        )
        .await
        .unwrap();

    check_result(result);

    println!("--- checking try_get_with ---");

    let result = cache
        .try_get_with(key.clone(), {
            future::ok::<u32, u32>(init(cache.clone(), &key, 3).await)
        })
        .await
        .unwrap();

    check_result(result);

    println!("--- checking get_with ---");

    let result = cache
        .get_with(key.clone(), init(cache.clone(), &key, 4))
        .await;

    check_result(result);
}
```
Produces this output
```
$ cargo run
--- checking try_get_with_by_ref ---
cache contains key but init triggered anyway
init ran to completion
result: 1
result was returned from cache
--- checking try_get_with ---
cache contains key but init triggered anyway
init ran to completion
result: 1
result was returned from cache
--- checking get_with ---
result: 1
result was returned from cache
```

Expected behavior: `try_get_with` and `try_get_with_by_ref` only run the provided init function when the key is not already contained in the cache, similar to `get_with`

**Comment by tatsuya6502** [comment] 2022-12-14 14:33
Thank you for reporting the issue. I am a bit busy this week, and I am hoping I can look after this in next week (the week of Dec 19, 2022). Sorry for the inconvenience.

**Comment by tatsuya6502** [comment] 2022-12-14 15:49
Ah, I believe this is the expected behavior. When `futures::future::ok` is called, its argument (the async function `init`) has been already resolved because of the `await`.

This code fragment will illustrate the behavior:

```rust
use futures::future;
use std::time::Duration;

async fn init(value: u32) -> u32 {
    println!("init triggered with {}", value);
    tokio::time::sleep(Duration::from_millis(1000)).await;
    println!("init ran to completion");
    value
}

#[tokio::main]
async fn main() {
    // We do not do `.await` on the  `_future`, but the init future
    // should have been resolved. This is because `ok` expects a `u32`
    // value as the argument, rather than `impl Future<Output=u32>`.
    let _future = future::ok::<_, u32>(init(2).await);
    let _future = future::ok::<_, u32>(init(3).await);
}
```

Output:

```console
init triggered with 2
init ran to completion
init triggered with 3
init ran to completion
```

You can fix the example by using `async` block instead of `futures::future::ok`:

```rust
use moka::future::Cache;
use std::convert::Infallible;
use std::hash::Hash;
use std::path::PathBuf;
use std::time::Duration;

async fn init<K: Hash + Eq + Send + Sync + Clone + 'static>(
    cache: Cache<K, u32>,
    key: &K,
    value: u32,
) -> u32 {
    if cache.contains_key(&key) {
        println!("cache contains key but init triggered anyway");
    }
    tokio::time::sleep(Duration::from_millis(1000)).await;
    println!("init ran to completion");
    value
}

fn check_result(result: u32) {
    println!("result: {:?}", &result);
    println!(
        "result was returned from {}",
        if result == 1 {
            "cache"
        } else {
            "init function"
        }
    );
}

#[tokio::main]
async fn main() {
    let cache = Cache::new(100);

    let key = PathBuf::from("asdf");

    cache.insert(key.clone(), 1).await;

    println!("--- checking try_get_with_by_ref ---");

    let result = cache
        .try_get_with_by_ref(&key, async {
            Ok(init(cache.clone(), &key, 2).await) as Result<u32, Infallible>
        })
        .await
        .unwrap();

    check_result(result);

    println!("--- checking try_get_with ---");

    let result = cache
        .try_get_with(key.clone(), async {
            Ok(init(cache.clone(), &key, 3).await) as Result<u32, Infallible>
        })
        .await
        .unwrap();

    check_result(result);

    println!("--- checking get_with ---");

    let result = cache
        .get_with(key.clone(), init(cache.clone(), &key, 4))
        .await;

    check_result(result);
}
```

Output:

```console
--- checking try_get_with_by_ref ---
result: 1
result was returned from cache
--- checking try_get_with ---
result: 1
result was returned from cache
--- checking get_with ---
result: 1
result was returned from cache
```

**Comment by tatsuya6502** [comment] 2022-12-16 21:32
Closing this issue. Please reopen if needed.

**Closed by tatsuya6502** 2022-12-16 21:32 UTC

**Comment by dannygale** [comment] 2022-12-27 23:23
Ahh, thanks, my mistake
